# -*- coding: utf-8 -*-
"""NaiveBais-Using-SmoteResampledData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gX3isMv5eCl6ZMVoq4-yMGWphqgeVVso

*Assuming that the necessary libraries are imported

SMOTE RESAMPLED DATA
NAIVE BIAS
"""

from sklearn.naive_bayes import MultinomialNB

# Initialize Naive Bayes model
nb_model = MultinomialNB()

# No hyperparameter tuning for Naive Bayes, just fit and predict
nb_model.fit(X_train_resampled, y_train_resampled)
y_pred_nb = nb_model.predict(X_test)

# Print classification report
print("Classification Report (Naive Bayes):")
print(classification_report(y_test, y_pred_nb))