# -*- coding: utf-8 -*-
"""SVM-RandomizedSearchCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155shg7yD8zXaVBVuuYRprXd3_Ou8fBCP

*assuming necessary libraries are imported

SVM RANDOMIZED SERACH CV
"""

from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from sklearn.metrics import classification_report

# Define the pipeline with SMOTE and SVM
pipeline_svm = Pipeline([
    ('smote', SMOTE(random_state=42)),
    ('svc', SVC())
])

# Define parameters for hyperparameter tuning
param_grid_svm = {
    'svc__C': [0.1, 1, 10, 100],
    'svc__gamma': ['scale', 'auto'],
    'svc__kernel': ['linear', 'rbf', 'poly', 'sigmoid']
}

# Perform RandomizedSearchCV
svm_random_search = RandomizedSearchCV(pipeline_svm, param_distributions=param_grid_svm, n_iter=20, scoring='accuracy', cv=5, verbose=1, random_state=42)
svm_random_search.fit(X_train, y_train)

# Get the best model and evaluate on test set
best_svm = svm_random_search.best_estimator_
y_pred_svm = best_svm.predict(X_test)

# Print best parameters and classification report
print("Best Parameters (SVM):", svm_random_search.best_params_)
print("Accuracy (SVM):", svm_random_search.best_score_)
print("Classification Report (SVM):")
print(classification_report(y_test, y_pred_svm))